# Checklist {.unnumbered}

## General Guidelines

### Working principles for copy editors

In their work, copyeditors should be encouraged to observe certain principles. They should:

-   make essential changes only — if authors write correctly, their own wording should be kept;

-   make the manuscript easy to read and correct;

-   comment constructively when comment is needed;

-   look for answers from reference sources or previous issues of the journal before putting queries to an author;

-   keep queries to the author short and to the point.

### Copyediting procedures

One possible method of working is to deal with all the required levels of editing together, during one or two readings of a manuscript, followed by a separate stage for cross-checking and styling references. Another method is to edit the language first, at the same time as substantive editing if this is required, followed by format and mechanical style, again with reference checking as a separate stage.

## Editing Checklists

### CJILS Specific Requirements

-   [ ] Does the first page include all the required information (**title, author names, institution, abstract, keywords, Orcid ID if known**)?

-   [ ] Are the authors’ names and institution correct?

-   [ ] Is an abstract of the correct kind included (**50-100 words in length**)?

-   [ ] Is it unblinded? If not, check in with the Production Editor.

-   [ ] Is the About the Author(s) statement properly positioned and marked?

-   [ ] Are acknowledgements, if added, properly positioned and marked?

-   [ ] Do the references have DOIs or links where applicable? Do the links work?

-   [ ] Does the manuscript follow Chicago Author-Date style? Including in-text citations and references?

### Level 1. Checklist for mechanical style and format of text

-   [ ] Is the manuscript complete?

-   [ ] Are all files with tables etc. included?

-   [ ] If an appendix is included, is it properly positioned and marked?

-   [ ] Are endnotes/footnotes, if any, clearly positioned and linked to their indicator symbols in the text?

-   [ ] Are spelling and punctuation consistent? Is the spacing after punctuation correct?

-   [ ] Are extracts and quotations clearly indicated and acknowledged?

-   [ ] Are capital letters, small capitals, italics, and bold type clearly marked and used correctly and consistently?

-   [ ] Are abbreviations and symbols used correctly and consistently? Are abbreviations other than recognized abbreviations for units explained at first mention and later used consistently?

-   [ ] Are special scripts and accents clearly presented and used consistently?

-   [ ] Are numerals correctly written? (see below)

-   [ ] Are parentheses and brackets properly paired off?

### Level 2. Checklist for tables and figures

-   [ ] Are tables and figures referred to in the text in correct numerical order?

-   [ ] Do tables and figures show what the text says they show?

-   [ ] Do numbers and other references to table and figure contents match any details cited in the text?

#### Tables

-   [ ] Do tables have clear titles, column headings, and footnotes, as needed?

-   [ ]  Have abbreviations in tables been explained?

-   [ ]  Is the arithmetic in tables correct — do numbers in table columns add up correctly, and are percentages correct?

#### Figures

-   [ ] Are line drawings clearly drawn?

-   [ ] Are photographs of good quality?

-   [ ] If figures have been supplied electronically, are size and resolution acceptable?

### Level 3. Checklist for citations and bibliographical references

-   [ ] Are all citations in the text included in the reference list?

-   [ ] Are all references in the list cited in the text?

-   [ ] Are in-text citations and references unblinded?

-   [ ] If names and dates are given in the text, do they agree with those in the list?

-   [ ] Does the form of citations in the text match Chicago Author-Date?

-   [ ] Are all the required parts of references included in the reference list according to Chicago Author-Date?

-   [ ] Are those parts in the correct sequence and form?

-   [ ] Is the punctuation correct?

-   [ ] Is the typographical style (case, italics, bold) correct?

-   [ ] If journal titles are abbreviated, are abbreviations correct?

-   [ ]  Does the form of references to books, reports, and other types of publication match the Chicago Author-Date?

-   [ ] Are DOIs and links to e-articles present and valid?

### Level 4. A checklist for language editing

#### Spelling and punctuation

-   [ ] Is the spelling correct and consistent, according to house style?

-   [ ] Are quotation marks correctly used according to Chicago Author-Date?

-   [ ] Are parentheses correctly placed?

-   [ ] Are commas correctly used?

-   [ ] Are hyphens and en and em dashes correctly used with proper spacing?

-   [ ] Have apostrophes been kept to a minimum and been correctly used?

-   [ ] Are colons and semicolons correctly used?

-   [ ] Have exclamation marks and dashes been kept to a minimum?

#### Grammar and syntax

-   [ ] Has the passive voice been kept to a reasonable minimum?

-   [ ] Are tenses used correctly and consistently?

-   [ ] Have strings of three or more nouns been kept to a minimum?

-   [ ] Have words been used in the right order?

#### Usage

-   [ ] Is usage correct according to current recommendations?

-   [ ] Have words been used with precision?

-   [ ] Have the simplest words and the simplest ways of writing been used?

-   [ ] Have sexist, racist, or dehumanizing terms been transformed or removed?

*Adapted from O’Connor, Maeve, Margaret Cooter, and Sylwia B. Ufnalska. "1.1: Copy-editing scientific papers." P. Smart, H. Maisonneuve & A. Polderman, eds (2013).*