# Overview {.unnumbered}

## Introduction

This documentation is for CJILS Production Managers, Copyeditors, and Layout Editors and gives a detailed description of the roles and responsibilities for each. All production processes are managed through the CJILS OJS instance hosted by the University of Western Ontario. [link](https://ojs.lib.uwo.ca/index.php/cjils/submissions) Currently, we are using OJS 3.3 for this journal. You can reference PKP documentation [here](https://docs.pkp.sfu.ca/learning-ojs/3.3/en/) or a video playlist [here](https://www.youtube.com/watch?v=5Hwkqj4Jvew&list=PLg358gdRUrDUKJbWtr4bgy133_jwoiqoF&index=1). OJS will be updated to 3.5 in mid-October to mid-December of 2026.

Additionally, we use an subscription to Overleaf for formatting the proofs and final versions of each work. You can find the login for our Overleaf account [here](https://www.overleaf.com/project). More details on how to set up each Overleaf project will be included in the Copyediting section below.

Overall, our workflow starts with the manuscript submission from an author or authors. If selected by the Chief Editor, it will be assigned to the Production Manager to send out requests for peer-review. Upon receiving peer-reviews, the Production Manager sends the reviews or recommendations to the authors. If revisions are required, the authors may resubmit another version for consideration by the Chief Editor who will determine if another round of reviews is necessary. If approved to move forward, the work then enters the Copyediting stage where the Production Manager will assign a CopyEditor. Once the Copyeditor has created a copy for revisions, it is sent to the author for review and comment. If approved, it moves forward to the Layout Editor and a proof is sent to the authors for their approval. Upon approval, the Final Proof is created and then sent to the authors for a final check. Once approved, the work is then scheduled for publication. Below, we have detailed steps for each process.

## Manuscript submission

## Peer-review

## Copyediting

Workload: Our goal is to spread the workload as evenly as possible so you may receive submissions at any point during the year. Basic Production Process: 1. The Copyeditor downloads the Draft file and makes copyedits using Track Changes. 2. The Copyeditor sends the article with revisions back to the author. 3. The author makes changes and returns the article back to the Copyeditor. 4. The Copyeditor prepares a clean, edited copy and notifies the Production Editor that it is ready for layout. 5. The Layout Editor will apply CJILS formatting and prepare a galley. 6. The proof will be sent to the author for review and returns the article back to the editors. 7. That proof will be sent to the Proofreader to scan for any copyediting or formatting errors and returns the article back to the editors. 8. The Layout Editor then makes any changes, prepares metadata, and prepares accessibility features. 9. The article is ready for publication. Production Timeline: The table below shows the production timeline for each article. For most submissions, the initial copyedit, final copyedit and final proofread should be completed and returned within two weeks. The timeline below also applies to the authors’ copyedits and proofreading (unless there are particularly substantial changes; defer to the Editor if you have any questions).

|  |  |  |  |  |  |
|----|----|----|----|----|----|
| Copyedit 1 (2 weeks) | Author CE (2 week) | Copyedit 2 (2 week) | Layout (2 weeks) | Author Proof (1 week) | Final Proof (2 weeks)\| |

If you believe you will be unable to complete a submission in the usual timeframe, please contact the Production Editor to let them know. Depending on your availability, the timeline may either be adjusted or reassigned to another copyeditor.

-   Notifying a copyeditor;

-   copyediting guides and links \[here\](<https://drive.google.com/drive/folders/1aR0qlDHwu-1i6MnpPUo66YAkfg8yHRWn?usp=sharing>)

-   emailing through CJILS copyeding group in the Dal MS mail;

-   assigning by tiers; French vs English versions;

-   responsibilities of the copyeditor;

-   uploading last draft from the copyeditor

-   discussions between copyeditor and author

-   approving copyedited version, sending to production

## Production

## Publication