# Main text {.unnumbered}

## Overview

## Sections

```{latex}
\section{level 1 heading}
\subsection{level 2 heading}
\subsubsection{level 3 heading}
\subsubsubsection{level 4 heading}
```

## Paragraphs

There is no particular code to write for a paragraph. Just put the text, and put a line break in between paragraphs.

```{latex}
This is a paragraph.

This is another paragraph.
```

## Lists

### Bullet points

```{latex}
\begin{itemize}
  \item This is the first bullet point
  \item This is the second bullet point
  \item this is the third bullet point
\end{itemize}
```

### Numbered lists

```{latex}
\begin{enumerate}
  \item This is the first item
  \item This is the second item
  \item this is the third item
\end{enumerate}
```

### Spacing between list items

By default there will be a empty line between bullet points. That's usually undesirable unless the bullets contain long multi-line text and spacing them out improves readability. So you will often use **\\tightlist** to reduce the space between the items. Like this:

```{latex}
\begin{itemize}
  \tightlist
  \item This is the first bullet point
  \item This is the second bullet point
  \item this is the third bullet point
\end{itemize}
```

## Footnotes

```{latex}
This is a text.\footnote{and this is the footnote for that text.}
```

## Citations

At this point we write citations manually, directly in the paragraph so there is nothing specific to do other than making sure they are in proper APA 7 format.

```{latex}
This is a bit of text in a paragraph (Some author, 2022).
```

## Quotes

Quotes can go straight in the text when less than 40 words or three lines, otherwise use a long quote.

```{latex}
\begin{quote}
  This is a quote 
\end{quote}
```

## Hyperlinks

use the **\\url{}**

```{latex}
\url{https://www.somewebsite.ca/}
```
