---
format:
  html:
    toc: false
    toc-location: body
    toc-depth: 2
---

# Introduction {.unnumbered}

Welcome to the official guide for supporting the copyediting process of manuscripts submitted to the *Canadian Journal of Information and Library Science (CJILS)*. This resource is designed to assist the journal editors, managers, and copyeditors editors in preparing CJILS articles for publication—ensuring clarity, consistency, and compliance with journal style.

Whether you're a seasoned language professional or newly joining the CJILS editorial workflow, this guide provides step-by-step instructions, templates, checklists, and formatting support tailored to the specific needs of our journal.

## Contents

### Section 1. Copyediting Process and Tools
- [Overview](general.qmd)
- [Open Journal System (OJS)](ojs.qmd)
- [Overleaf](overleaf.qmd)
- [Checklist](checklist.qmd)

### Section 2. LaTeX guide
- [Header](header.qmd)
- [Title Page](title-page.qmd)
- [Main Text](main.qmd)
- [Figures](figures.qmd)
- [Tables](tables.qmd)
- [References](references.qmd)
- [Appendices](appendices.qmd)


