# Tables {.unnumbered}

## One vs two column tables

### Single Column Table 

```{latex}
\begin{table}
  \begin{tabular}
  \end{tabular}
\end{table}
```

### Two-Column Table

```{latex}
\begin{table*}
  \begin{tabularx}
  \end{tabularx}
\end{table*}
```

### Long Tables

#### single column

```{}
```

#### Two column

```{latex}
\begin{table*}
  \begin{longtable}
  \end{longtable}
\end{table*}
```

## Table Position

LaTeX will not always put your table exactly where you placed it in the text due to its internal layout rules. **If** the default position is not ideal, you can attempt giving LaTeX some instructions to better position the table.

If you're happy with the table placement, you don't have to do anything.

### Specifiers

| Specifier | Meaning                                                     |
|-----------|-------------------------------------------------------------|
| h         | Place the table **here**, roughly at the current location   |
| t         | Place the table at the **top** of the page                  |
| b         | Place the table at the **bottom** of the page               |
| p         | Place the table on a **separate page** for floats only      |
| !         | Override LaTeX’s internal float placement rules             |
| H         | Place the table **exactly here** (requires `float` package) |

### Example

```{latex}
\begin{table*}
  \begin{longtable}
  \end{longtable}
\end{table*}
```

### Tips and tricks

-   You can combine them (e.g.,`[htbp!]` )to give LaTeX flexibility while nudging it toward your preferred location.

-   It is recommended not to use \[h\] alone, as it can sometimes be ignored. Prefer \[ht\] or \[htbp\].

::: callout-tip
## Do not fight LaTeX

Often, you might find that latex is not at all cooperating with you when it comes to positioning tables. My advice is to not die on that hill. Your table is showing up somewhere in the document. It looks good, but it's not where you want it, so you spend a few minutes trying different strategies to move it to a better spot. No luck? Just move on.
:::

## Caption

The caption is the first element in the table.

```{latex}
\caption{\label{tbl-mytable}\textit{title of the table goes here}}
```

## Columns

```{latex}
\begin{tabularx}{\textwidth}{%
  >{\raggedright\arraybackslash}p{1.5in} 
  >{\raggedright\arraybackslash}p{2.5in}
  >{\raggedleft\arraybackslash}p{2.5in} 
}
```

### Alignment

### Column width

**{\\textwidth}**

**p{1.5in}**

## Rows

## Borders

## Notes

## Layout

## Tips and tricks

### Copy pasting from Word

### Copilot
